# This file is generated by generate_cesr_controls.py from cesr.bmad.
# Do not hand-edit the coefficient tables. The runtime implementation below may
# be edited, but regenerate carefully because this script rewrites the full file.

using Beamlines

"""One mutable scalar used by a CESR control knob."""
mutable struct CESRControlKnob{T}
    value::T
end

"""All CESR overlay and group knobs attached to one ring."""
struct CESRControls{T}
    overlays::Dict{String,CESRControlKnob{T}}
    groups::Dict{String,CESRControlKnob{T}}
end

"""A physical element attribute driven by one control knob."""
struct CESRControlContribution{T}
    knob::CESRControlKnob{T}
    coefficient::Float64
end

const CESR_OVERLAY_TERMS = [
    ("H01W", "HKICK", "HV01W", 1.0),
    ("V01W", "VKICK", "HV01W", 1.0),
    ("HB01", "HKICK", "B04W", 0.5),
    ("HB01", "HKICK", "B05W", 0.5),
    ("H02W", "HKICK", "B03W", 1.0),
    ("V02W", "VKICK", "SK_Q03W", 1.0),
    ("HB02", "HKICK", "B06W", 0.5),
    ("HB02", "HKICK", "B07W", 0.5),
    ("H03W", "HKICK", "B03AW", 1.0),
    ("HB03", "HKICK", "B47AW", 1.0),
    ("H04W", "HKICK", "B04W", 1.0),
    ("V04W", "VKICK", "SK_Q04W", 1.0),
    ("HB04", "HKICK", "B47AE", 1.0),
    ("V05W", "VKICK", "SK_Q05W", 1.0),
    ("HB05", "HKICK", "B07E", 0.5),
    ("HB05", "HKICK", "B06E", 0.5),
    ("V06W", "VKICK", "SK_Q06W", 1.0),
    ("HB06", "HKICK", "B05E", 0.5),
    ("HB06", "HKICK", "B04E", 0.5),
    ("V07W", "VKICK", "VKICK_07W", 1.0),
    ("H08W", "HKICK", "HKICK_08W", 1.0),
    ("V08W", "VKICK", "SEX_08W", 1.0),
    ("V09W", "VKICK", "VKICK_09W", 1.0),
    ("H10W", "HKICK", "B11W", 1.0),
    ("V10W", "VKICK", "VKICK_10W", 1.0),
    ("V11W", "VKICK", "SEX_11W", 1.0),
    ("H12W", "HKICK", "B12W", 0.5),
    ("H12W", "HKICK", "B13W", 0.5),
    ("V13W", "VKICK", "SEX_13W", 1.0),
    ("H14W", "HKICK", "B14W", 0.5),
    ("H14W", "HKICK", "B15W", 0.5),
    ("V15W", "VKICK", "SEX_15W", 1.0),
    ("H16W", "HKICK", "B16W", 0.5),
    ("H16W", "HKICK", "B17W", 0.5),
    ("V16W", "VKICK", "VKICK_16W", 1.0),
    ("V17W", "VKICK", "SEX_17W", 1.0),
    ("H18W", "HKICK", "B18W", 1.0),
    ("V19W", "VKICK", "SEX_19W", 1.0),
    ("H20W", "HKICK", "B20W", 0.5),
    ("H20W", "HKICK", "B21W", 0.5),
    ("V21W", "VKICK", "SEX_21W", 1.0),
    ("H22W", "HKICK", "B22W", 0.5),
    ("H22W", "HKICK", "B23W", 0.5),
    ("V23W", "VKICK", "SEX_23W", 1.0),
    ("H24W", "HKICK", "B24W", 0.5),
    ("H24W", "HKICK", "B25W", 0.5),
    ("V25W", "VKICK", "SEX_25W", 1.0),
    ("H26W", "HKICK", "B26W", 0.5),
    ("H26W", "HKICK", "B27W", 0.5),
    ("V27W", "VKICK", "SEX_27W", 1.0),
    ("H28W", "HKICK", "B28W", 0.5),
    ("H28W", "HKICK", "B29W", 0.5),
    ("V29W", "VKICK", "SEX_29W", 1.0),
    ("H30W", "HKICK", "B30W", 0.5),
    ("H30W", "HKICK", "B31W", 0.5),
    ("V31W", "VKICK", "SEX_31W", 1.0),
    ("H32W", "HKICK", "B32W", 0.5),
    ("H32W", "HKICK", "B33W", 0.5),
    ("V33W", "VKICK", "SEX_33W", 1.0),
    ("H34W", "HKICK", "B35W", 1.0),
    ("V35W", "VKICK", "SEX_35W", 1.0),
    ("H36W", "HKICK", "B36W", 0.5),
    ("H36W", "HKICK", "B37W", 0.5),
    ("V37W", "VKICK", "SEX_37W", 1.0),
    ("H38W", "HKICK", "B38W", 0.5),
    ("H38W", "HKICK", "B39W", 0.5),
    ("V39W", "VKICK", "SEX_39W", 1.0),
    ("H40W", "HKICK", "B40W", 0.5),
    ("H40W", "HKICK", "B41W", 0.5),
    ("V41W", "VKICK", "SEX_41W", 1.0),
    ("H42W", "HKICK", "B42W", 0.5),
    ("H42W", "HKICK", "B43W", 0.5),
    ("V43W", "VKICK", "SEX_43W", 1.0),
    ("H44W", "HKICK", "B44W", 1.0),
    ("V45W", "VKICK", "SEX_45W", 1.0),
    ("H46W", "HKICK", "B46W", 1.0),
    ("H47W", "HKICK", "B48W", 1.0),
    ("V47W", "VKICK", "VKICK_47W", 1.0),
    ("V48W", "VKICK", "VKICK_48W", 1.0),
    ("H49W", "HKICK", "HKICK_49W", 1.0),
    ("V49W", "VKICK", "VKICK_49W", 1.0),
    ("H49E", "HKICK", "HKICK_49E", 1.0),
    ("V49E", "VKICK", "VKICK_49E", 1.0),
    ("V48E", "VKICK", "VKICK_48E", 1.0),
    ("H47E", "HKICK", "B48E", 1.0),
    ("V47E", "VKICK", "VKICK_47E", 1.0),
    ("H46E", "HKICK", "B46E", 1.0),
    ("V45E", "VKICK", "SEX_45E", 1.0),
    ("H44E", "HKICK", "B44E", 1.0),
    ("V43E", "VKICK", "SEX_43E", 1.0),
    ("H42E", "HKICK", "B43E", 0.5),
    ("H42E", "HKICK", "B42E", 0.5),
    ("V41E", "VKICK", "SEX_41E", 1.0),
    ("H40E", "HKICK", "B41E", 0.5),
    ("H40E", "HKICK", "B40E", 0.5),
    ("V39E", "VKICK", "SEX_39E", 1.0),
    ("H38E", "HKICK", "B39E", 0.5),
    ("H38E", "HKICK", "B38E", 0.5),
    ("V37E", "VKICK", "SEX_37E", 1.0),
    ("H36E", "HKICK", "B37E", 0.5),
    ("H36E", "HKICK", "B36E", 0.5),
    ("V35E", "VKICK", "SEX_35E", 1.0),
    ("H34E", "HKICK", "B35E", 1.0),
    ("V34E", "VKICK", "SEX_34E", 1.0),
    ("V33E", "VKICK", "SEX_33E", 1.0),
    ("H32E", "HKICK", "B33E", 0.5),
    ("H32E", "HKICK", "B32E", 0.5),
    ("V31E", "VKICK", "SEX_31E", 1.0),
    ("H30E", "HKICK", "B31E", 0.5),
    ("H30E", "HKICK", "B30E", 0.5),
    ("V29E", "VKICK", "SEX_29E", 1.0),
    ("H28E", "HKICK", "B29E", 0.5),
    ("H28E", "HKICK", "B28E", 0.5),
    ("V27E", "VKICK", "SEX_27E", 1.0),
    ("H26E", "HKICK", "B27E", 0.5),
    ("H26E", "HKICK", "B26E", 0.5),
    ("V25E", "VKICK", "SEX_25E", 1.0),
    ("H24E", "HKICK", "B25E", 0.5),
    ("H24E", "HKICK", "B24E", 0.5),
    ("V23E", "VKICK", "SEX_23E", 1.0),
    ("H22E", "HKICK", "B23E", 0.5),
    ("H22E", "HKICK", "B22E", 0.5),
    ("V21E", "VKICK", "SEX_21E", 1.0),
    ("H20E", "HKICK", "B21E", 0.5),
    ("H20E", "HKICK", "B20E", 0.5),
    ("V19E", "VKICK", "SEX_19E", 1.0),
    ("H18E", "HKICK", "B18E", 1.0),
    ("V17E", "VKICK", "SEX_17E", 1.0),
    ("H16E", "HKICK", "B17E", 0.5),
    ("H16E", "HKICK", "B16E", 0.5),
    ("V15E", "VKICK", "SEX_15E", 1.0),
    ("H14E", "HKICK", "B15E", 0.5),
    ("H14E", "HKICK", "B14E", 0.5),
    ("V13E", "VKICK", "SEX_13E", 1.0),
    ("H12E", "HKICK", "B13E", 0.5),
    ("H12E", "HKICK", "B12E", 0.5),
    ("V11E", "VKICK", "SEX_11E", 1.0),
    ("H10E", "HKICK", "B11E", 1.0),
    ("V09E", "VKICK", "VKICK_09E", 1.0),
    ("H08E", "HKICK", "HKICK_08E", 0.5),
    ("H08E", "HKICK", "HKICK_07E", 0.5),
    ("V08E", "VKICK", "VKICK_08E", 1.0),
    ("V07E", "VKICK", "VKICK_07E", 1.0),
    ("V06E", "VKICK", "SK_Q06E", 1.0),
    ("V05E", "VKICK", "SK_Q05E", 1.0),
    ("H04E", "HKICK", "B04E", 1.0),
    ("V04E", "VKICK", "SK_Q04E", 1.0),
    ("H03E", "HKICK", "B03AE", 1.0),
    ("H02E", "HKICK", "B03E", 1.0),
    ("V02E", "VKICK", "SK_Q03E", 1.0),
    ("H01E", "HKICK", "HV01E", 1.0),
    ("V01E", "VKICK", "HV01E", 1.0),
]

const CESR_GROUP_TERMS = [
    ("RAW_XQUNE_1", "SEX_08W", "K2", -0.0006415),
    ("RAW_XQUNE_1", "SEX_08E", "K2", -0.0006847),
    ("RAW_XQUNE_1", "SEX_09W", "K2", -0.01957),
    ("RAW_XQUNE_1", "SEX_09E", "K2", -0.01964),
    ("RAW_XQUNE_1", "SEX_10W", "K2", -0.02325),
    ("RAW_XQUNE_1", "SEX_10E", "K2", -0.0233),
    ("RAW_XQUNE_1", "SEX_11W", "K2", -0.04536),
    ("RAW_XQUNE_1", "SEX_11E", "K2", -0.04537),
    ("RAW_XQUNE_1", "SEX_12W", "K2", 0.01334),
    ("RAW_XQUNE_1", "SEX_12E", "K2", 0.01337),
    ("RAW_XQUNE_1", "SEX_13W", "K2", 0.04463),
    ("RAW_XQUNE_1", "SEX_13E", "K2", 0.04469),
    ("RAW_XQUNE_1", "SEX_14W", "K2", -0.002724),
    ("RAW_XQUNE_1", "SEX_14E", "K2", -0.002685),
    ("RAW_XQUNE_1", "SEX_15W", "K2", -0.07129),
    ("RAW_XQUNE_1", "SEX_15E", "K2", -0.0713),
    ("RAW_XQUNE_1", "SEX_16W", "K2", 0.01784),
    ("RAW_XQUNE_1", "SEX_16E", "K2", 0.01781),
    ("RAW_XQUNE_1", "SEX_17W", "K2", -0.1263),
    ("RAW_XQUNE_1", "SEX_17E", "K2", -0.1263),
    ("RAW_XQUNE_1", "SEX_18W", "K2", 0.05265),
    ("RAW_XQUNE_1", "SEX_18E", "K2", 0.05263),
    ("RAW_XQUNE_1", "SEX_19W", "K2", -0.1208),
    ("RAW_XQUNE_1", "SEX_19E", "K2", -0.1208),
    ("RAW_XQUNE_1", "SEX_20W", "K2", 0.04034),
    ("RAW_XQUNE_1", "SEX_20E", "K2", 0.04033),
    ("RAW_XQUNE_1", "SEX_21W", "K2", -0.1666),
    ("RAW_XQUNE_1", "SEX_21E", "K2", -0.1666),
    ("RAW_XQUNE_1", "SEX_22W", "K2", 0.03012),
    ("RAW_XQUNE_1", "SEX_22E", "K2", 0.03014),
    ("RAW_XQUNE_1", "SEX_23W", "K2", -0.06296),
    ("RAW_XQUNE_1", "SEX_23E", "K2", -0.06292),
    ("RAW_XQUNE_1", "SEX_24W", "K2", 0.01353),
    ("RAW_XQUNE_1", "SEX_24E", "K2", 0.01356),
    ("RAW_XQUNE_1", "SEX_25W", "K2", -0.1196),
    ("RAW_XQUNE_1", "SEX_25E", "K2", -0.1195),
    ("RAW_XQUNE_1", "SEX_26W", "K2", 0.0055),
    ("RAW_XQUNE_1", "SEX_26E", "K2", 0.005495),
    ("RAW_XQUNE_1", "SEX_27W", "K2", -0.0593),
    ("RAW_XQUNE_1", "SEX_27E", "K2", -0.05934),
    ("RAW_XQUNE_1", "SEX_28W", "K2", -0.0006739),
    ("RAW_XQUNE_1", "SEX_28E", "K2", -0.0007063),
    ("RAW_XQUNE_1", "SEX_29W", "K2", -0.01762),
    ("RAW_XQUNE_1", "SEX_29E", "K2", -0.01767),
    ("RAW_XQUNE_1", "SEX_30W", "K2", 0.01027),
    ("RAW_XQUNE_1", "SEX_30E", "K2", 0.01025),
    ("RAW_XQUNE_1", "SEX_31W", "K2", -0.09168),
    ("RAW_XQUNE_1", "SEX_31E", "K2", -0.09166),
    ("RAW_XQUNE_1", "SEX_32W", "K2", 0.008794),
    ("RAW_XQUNE_1", "SEX_32E", "K2", 0.008838),
    ("RAW_XQUNE_1", "SEX_33W", "K2", -0.06525),
    ("RAW_XQUNE_1", "SEX_33E", "K2", -0.06515),
    ("RAW_XQUNE_1", "SEX_34W", "K2", 0.01937),
    ("RAW_XQUNE_1", "SEX_34E", "K2", 0.01944),
    ("RAW_XQUNE_1", "SEX_35W", "K2", -0.06681),
    ("RAW_XQUNE_1", "SEX_35E", "K2", -0.06675),
    ("RAW_XQUNE_1", "SEX_36W", "K2", 0.02846),
    ("RAW_XQUNE_1", "SEX_36E", "K2", 0.02845),
    ("RAW_XQUNE_1", "SEX_37W", "K2", -0.08956),
    ("RAW_XQUNE_1", "SEX_37E", "K2", -0.08961),
    ("RAW_XQUNE_1", "SEX_38W", "K2", 0.0161),
    ("RAW_XQUNE_1", "SEX_38E", "K2", 0.01606),
    ("RAW_XQUNE_1", "SEX_39W", "K2", -0.04658),
    ("RAW_XQUNE_1", "SEX_39E", "K2", -0.04663),
    ("RAW_XQUNE_1", "SEX_40W", "K2", 0.00389),
    ("RAW_XQUNE_1", "SEX_40E", "K2", 0.003868),
    ("RAW_XQUNE_1", "SEX_41W", "K2", -0.09697),
    ("RAW_XQUNE_1", "SEX_41E", "K2", -0.09697),
    ("RAW_XQUNE_1", "SEX_42W", "K2", 0.01036),
    ("RAW_XQUNE_1", "SEX_42E", "K2", 0.01039),
    ("RAW_XQUNE_1", "SEX_43W", "K2", 0.0),
    ("RAW_XQUNE_1", "SEX_43E", "K2", 0.0),
    ("RAW_XQUNE_1", "SEX_44W", "K2", -0.0267),
    ("RAW_XQUNE_1", "SEX_44E", "K2", -0.02664),
    ("RAW_XQUNE_1", "SEX_45W", "K2", -0.007145),
    ("RAW_XQUNE_1", "SEX_45E", "K2", -0.007119),
    ("RAW_XQUNE_2", "SEX_08W", "K2", 0.02652),
    ("RAW_XQUNE_2", "SEX_08E", "K2", 0.02661),
    ("RAW_XQUNE_2", "SEX_09W", "K2", -0.104),
    ("RAW_XQUNE_2", "SEX_09E", "K2", -0.1039),
    ("RAW_XQUNE_2", "SEX_10W", "K2", 0.07574),
    ("RAW_XQUNE_2", "SEX_10E", "K2", 0.07583),
    ("RAW_XQUNE_2", "SEX_11W", "K2", -0.05316),
    ("RAW_XQUNE_2", "SEX_11E", "K2", -0.05316),
    ("RAW_XQUNE_2", "SEX_12W", "K2", 0.027),
    ("RAW_XQUNE_2", "SEX_12E", "K2", 0.02698),
    ("RAW_XQUNE_2", "SEX_13W", "K2", 0.06293),
    ("RAW_XQUNE_2", "SEX_13E", "K2", 0.06291),
    ("RAW_XQUNE_2", "SEX_14W", "K2", 0.03673),
    ("RAW_XQUNE_2", "SEX_14E", "K2", 0.03661),
    ("RAW_XQUNE_2", "SEX_15W", "K2", 0.02913),
    ("RAW_XQUNE_2", "SEX_15E", "K2", 0.02913),
    ("RAW_XQUNE_2", "SEX_16W", "K2", 0.01652),
    ("RAW_XQUNE_2", "SEX_16E", "K2", 0.01666),
    ("RAW_XQUNE_2", "SEX_17W", "K2", 0.05961),
    ("RAW_XQUNE_2", "SEX_17E", "K2", 0.05966),
    ("RAW_XQUNE_2", "SEX_18W", "K2", -0.01859),
    ("RAW_XQUNE_2", "SEX_18E", "K2", -0.01844),
    ("RAW_XQUNE_2", "SEX_19W", "K2", 0.04165),
    ("RAW_XQUNE_2", "SEX_19E", "K2", 0.04167),
    ("RAW_XQUNE_2", "SEX_20W", "K2", 0.00915),
    ("RAW_XQUNE_2", "SEX_20E", "K2", 0.009228),
    ("RAW_XQUNE_2", "SEX_21W", "K2", 0.02553),
    ("RAW_XQUNE_2", "SEX_21E", "K2", 0.02554),
    ("RAW_XQUNE_2", "SEX_22W", "K2", 0.08925),
    ("RAW_XQUNE_2", "SEX_22E", "K2", 0.08923),
    ("RAW_XQUNE_2", "SEX_23W", "K2", -0.1737),
    ("RAW_XQUNE_2", "SEX_23E", "K2", -0.1737),
    ("RAW_XQUNE_2", "SEX_24W", "K2", 0.05611),
    ("RAW_XQUNE_2", "SEX_24E", "K2", 0.056),
    ("RAW_XQUNE_2", "SEX_25W", "K2", -0.04878),
    ("RAW_XQUNE_2", "SEX_25E", "K2", -0.04879),
    ("RAW_XQUNE_2", "SEX_26W", "K2", 0.1061),
    ("RAW_XQUNE_2", "SEX_26E", "K2", 0.106),
    ("RAW_XQUNE_2", "SEX_27W", "K2", 0.002813),
    ("RAW_XQUNE_2", "SEX_27E", "K2", 0.002824),
    ("RAW_XQUNE_2", "SEX_28W", "K2", 0.07305),
    ("RAW_XQUNE_2", "SEX_28E", "K2", 0.07323),
    ("RAW_XQUNE_2", "SEX_29W", "K2", -0.08761),
    ("RAW_XQUNE_2", "SEX_29E", "K2", -0.08759),
    ("RAW_XQUNE_2", "SEX_30W", "K2", 0.06858),
    ("RAW_XQUNE_2", "SEX_30E", "K2", 0.06863),
    ("RAW_XQUNE_2", "SEX_31W", "K2", 0.01985),
    ("RAW_XQUNE_2", "SEX_31E", "K2", 0.01985),
    ("RAW_XQUNE_2", "SEX_32W", "K2", 0.09288),
    ("RAW_XQUNE_2", "SEX_32E", "K2", 0.09279),
    ("RAW_XQUNE_2", "SEX_33W", "K2", -0.05098),
    ("RAW_XQUNE_2", "SEX_33E", "K2", -0.05103),
    ("RAW_XQUNE_2", "SEX_34W", "K2", 0.05046),
    ("RAW_XQUNE_2", "SEX_34E", "K2", 0.05029),
    ("RAW_XQUNE_2", "SEX_35W", "K2", -0.0144),
    ("RAW_XQUNE_2", "SEX_35E", "K2", -0.01442),
    ("RAW_XQUNE_2", "SEX_36W", "K2", 0.06861),
    ("RAW_XQUNE_2", "SEX_36E", "K2", 0.06857),
    ("RAW_XQUNE_2", "SEX_37W", "K2", -0.008934),
    ("RAW_XQUNE_2", "SEX_37E", "K2", -0.008929),
    ("RAW_XQUNE_2", "SEX_38W", "K2", 0.05149),
    ("RAW_XQUNE_2", "SEX_38E", "K2", 0.05166),
    ("RAW_XQUNE_2", "SEX_39W", "K2", -0.09573),
    ("RAW_XQUNE_2", "SEX_39E", "K2", -0.09571),
    ("RAW_XQUNE_2", "SEX_40W", "K2", 0.0581),
    ("RAW_XQUNE_2", "SEX_40E", "K2", 0.05815),
    ("RAW_XQUNE_2", "SEX_41W", "K2", -0.04242),
    ("RAW_XQUNE_2", "SEX_41E", "K2", -0.04242),
    ("RAW_XQUNE_2", "SEX_42W", "K2", 0.0575),
    ("RAW_XQUNE_2", "SEX_42E", "K2", 0.05749),
    ("RAW_XQUNE_2", "SEX_43W", "K2", 0.0),
    ("RAW_XQUNE_2", "SEX_43E", "K2", 0.0),
    ("RAW_XQUNE_2", "SEX_44W", "K2", 0.05471),
    ("RAW_XQUNE_2", "SEX_44E", "K2", 0.0547),
    ("RAW_XQUNE_2", "SEX_45W", "K2", -0.01618),
    ("RAW_XQUNE_2", "SEX_45E", "K2", -0.01628),
    ("RAW_XQUNE_3", "SEX_08W", "K2", 0.01417),
    ("RAW_XQUNE_3", "SEX_08E", "K2", 0.01012),
    ("RAW_XQUNE_3", "SEX_09W", "K2", 0.04427),
    ("RAW_XQUNE_3", "SEX_09E", "K2", -0.3892),
    ("RAW_XQUNE_3", "SEX_10W", "K2", 0.01178),
    ("RAW_XQUNE_3", "SEX_10E", "K2", -0.007446),
    ("RAW_XQUNE_3", "SEX_11W", "K2", -0.02649),
    ("RAW_XQUNE_3", "SEX_11E", "K2", 0.1897),
    ("RAW_XQUNE_3", "SEX_12W", "K2", -0.06118),
    ("RAW_XQUNE_3", "SEX_12E", "K2", 0.1356),
    ("RAW_XQUNE_3", "SEX_13W", "K2", -0.3399),
    ("RAW_XQUNE_3", "SEX_13E", "K2", 0.7153),
    ("RAW_XQUNE_3", "SEX_14W", "K2", 0.07422),
    ("RAW_XQUNE_3", "SEX_14E", "K2", -0.03335),
    ("RAW_XQUNE_3", "SEX_15W", "K2", 0.4342),
    ("RAW_XQUNE_3", "SEX_15E", "K2", -0.1823),
    ("RAW_XQUNE_3", "SEX_16W", "K2", -0.1145),
    ("RAW_XQUNE_3", "SEX_16E", "K2", 0.07869),
    ("RAW_XQUNE_3", "SEX_17W", "K2", 0.4759),
    ("RAW_XQUNE_3", "SEX_17E", "K2", -0.124),
    ("RAW_XQUNE_3", "SEX_18W", "K2", -0.08022),
    ("RAW_XQUNE_3", "SEX_18E", "K2", 0.1503),
    ("RAW_XQUNE_3", "SEX_19W", "K2", -0.04074),
    ("RAW_XQUNE_3", "SEX_19E", "K2", -0.1468),
    ("RAW_XQUNE_3", "SEX_20W", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_20E", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_21W", "K2", -0.3891),
    ("RAW_XQUNE_3", "SEX_21E", "K2", 0.03532),
    ("RAW_XQUNE_3", "SEX_22W", "K2", 0.03136),
    ("RAW_XQUNE_3", "SEX_22E", "K2", -0.01032),
    ("RAW_XQUNE_3", "SEX_23W", "K2", -0.2135),
    ("RAW_XQUNE_3", "SEX_23E", "K2", 0.172),
    ("RAW_XQUNE_3", "SEX_24W", "K2", -0.03545),
    ("RAW_XQUNE_3", "SEX_24E", "K2", -0.0514),
    ("RAW_XQUNE_3", "SEX_25W", "K2", 0.03725),
    ("RAW_XQUNE_3", "SEX_25E", "K2", 0.01761),
    ("RAW_XQUNE_3", "SEX_26W", "K2", -0.1067),
    ("RAW_XQUNE_3", "SEX_26E", "K2", 0.0834),
    ("RAW_XQUNE_3", "SEX_27W", "K2", 0.357),
    ("RAW_XQUNE_3", "SEX_27E", "K2", -0.1867),
    ("RAW_XQUNE_3", "SEX_28W", "K2", -0.1148),
    ("RAW_XQUNE_3", "SEX_28E", "K2", 0.06794),
    ("RAW_XQUNE_3", "SEX_29W", "K2", 0.4248),
    ("RAW_XQUNE_3", "SEX_29E", "K2", -0.1996),
    ("RAW_XQUNE_3", "SEX_30W", "K2", -0.02974),
    ("RAW_XQUNE_3", "SEX_30E", "K2", -0.09303),
    ("RAW_XQUNE_3", "SEX_31W", "K2", -0.3219),
    ("RAW_XQUNE_3", "SEX_31E", "K2", 0.3315),
    ("RAW_XQUNE_3", "SEX_32W", "K2", -0.03694),
    ("RAW_XQUNE_3", "SEX_32E", "K2", -0.05439),
    ("RAW_XQUNE_3", "SEX_33W", "K2", -0.1373),
    ("RAW_XQUNE_3", "SEX_33E", "K2", 0.3055),
    ("RAW_XQUNE_3", "SEX_34W", "K2", 0.02058),
    ("RAW_XQUNE_3", "SEX_34E", "K2", -0.08466),
    ("RAW_XQUNE_3", "SEX_35W", "K2", -0.1522),
    ("RAW_XQUNE_3", "SEX_35E", "K2", 0.1872),
    ("RAW_XQUNE_3", "SEX_36W", "K2", 0.06698),
    ("RAW_XQUNE_3", "SEX_36E", "K2", 0.07407),
    ("RAW_XQUNE_3", "SEX_37W", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_37E", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_38W", "K2", 0.03752),
    ("RAW_XQUNE_3", "SEX_38E", "K2", 0.03157),
    ("RAW_XQUNE_3", "SEX_39W", "K2", -0.004309),
    ("RAW_XQUNE_3", "SEX_39E", "K2", -0.147),
    ("RAW_XQUNE_3", "SEX_40W", "K2", -0.0358),
    ("RAW_XQUNE_3", "SEX_40E", "K2", 0.01626),
    ("RAW_XQUNE_3", "SEX_41W", "K2", -0.2583),
    ("RAW_XQUNE_3", "SEX_41E", "K2", 0.1999),
    ("RAW_XQUNE_3", "SEX_42W", "K2", -0.009035),
    ("RAW_XQUNE_3", "SEX_42E", "K2", 0.03233),
    ("RAW_XQUNE_3", "SEX_43W", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_43E", "K2", 0.0),
    ("RAW_XQUNE_3", "SEX_44W", "K2", -0.06091),
    ("RAW_XQUNE_3", "SEX_44E", "K2", 0.1771),
    ("RAW_XQUNE_3", "SEX_45W", "K2", -0.003565),
    ("RAW_XQUNE_3", "SEX_45E", "K2", -0.03722),
    ("RAW_XQUNE_4", "SEX_08W", "K2", -0.01533),
    ("RAW_XQUNE_4", "SEX_08E", "K2", 0.02163),
    ("RAW_XQUNE_4", "SEX_09W", "K2", 0.1448),
    ("RAW_XQUNE_4", "SEX_09E", "K2", -0.07669),
    ("RAW_XQUNE_4", "SEX_10W", "K2", -0.2081),
    ("RAW_XQUNE_4", "SEX_10E", "K2", 0.01289),
    ("RAW_XQUNE_4", "SEX_11W", "K2", 0.08087),
    ("RAW_XQUNE_4", "SEX_11E", "K2", 0.1601),
    ("RAW_XQUNE_4", "SEX_12W", "K2", 0.2195),
    ("RAW_XQUNE_4", "SEX_12E", "K2", -0.08384),
    ("RAW_XQUNE_4", "SEX_13W", "K2", -0.2919),
    ("RAW_XQUNE_4", "SEX_13E", "K2", 0.1323),
    ("RAW_XQUNE_4", "SEX_14W", "K2", 0.1798),
    ("RAW_XQUNE_4", "SEX_14E", "K2", -0.1985),
    ("RAW_XQUNE_4", "SEX_15W", "K2", 0.04855),
    ("RAW_XQUNE_4", "SEX_15E", "K2", 0.08572),
    ("RAW_XQUNE_4", "SEX_16W", "K2", -0.04716),
    ("RAW_XQUNE_4", "SEX_16E", "K2", 0.005618),
    ("RAW_XQUNE_4", "SEX_17W", "K2", 0.3517),
    ("RAW_XQUNE_4", "SEX_17E", "K2", 0.1621),
    ("RAW_XQUNE_4", "SEX_18W", "K2", -0.2606),
    ("RAW_XQUNE_4", "SEX_18E", "K2", 0.2032),
    ("RAW_XQUNE_4", "SEX_19W", "K2", 0.1112),
    ("RAW_XQUNE_4", "SEX_19E", "K2", -0.04802),
    ("RAW_XQUNE_4", "SEX_20W", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_20E", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_21W", "K2", -0.1867),
    ("RAW_XQUNE_4", "SEX_21E", "K2", -0.06733),
    ("RAW_XQUNE_4", "SEX_22W", "K2", 0.1332),
    ("RAW_XQUNE_4", "SEX_22E", "K2", -0.08779),
    ("RAW_XQUNE_4", "SEX_23W", "K2", -0.1119),
    ("RAW_XQUNE_4", "SEX_23E", "K2", 0.02849),
    ("RAW_XQUNE_4", "SEX_24W", "K2", -0.05172),
    ("RAW_XQUNE_4", "SEX_24E", "K2", 0.04487),
    ("RAW_XQUNE_4", "SEX_25W", "K2", 0.02208),
    ("RAW_XQUNE_4", "SEX_25E", "K2", 0.03755),
    ("RAW_XQUNE_4", "SEX_26W", "K2", -0.5238),
    ("RAW_XQUNE_4", "SEX_26E", "K2", 0.5334),
    ("RAW_XQUNE_4", "SEX_27W", "K2", 0.08491),
    ("RAW_XQUNE_4", "SEX_27E", "K2", -0.05759),
    ("RAW_XQUNE_4", "SEX_28W", "K2", -0.2921),
    ("RAW_XQUNE_4", "SEX_28E", "K2", 0.2858),
    ("RAW_XQUNE_4", "SEX_29W", "K2", -0.08703),
    ("RAW_XQUNE_4", "SEX_29E", "K2", 0.05085),
    ("RAW_XQUNE_4", "SEX_30W", "K2", 0.3945),
    ("RAW_XQUNE_4", "SEX_30E", "K2", -0.4371),
    ("RAW_XQUNE_4", "SEX_31W", "K2", 0.01509),
    ("RAW_XQUNE_4", "SEX_31E", "K2", 0.1483),
    ("RAW_XQUNE_4", "SEX_32W", "K2", 0.1446),
    ("RAW_XQUNE_4", "SEX_32E", "K2", -0.1242),
    ("RAW_XQUNE_4", "SEX_33W", "K2", -0.09863),
    ("RAW_XQUNE_4", "SEX_33E", "K2", 0.08499),
    ("RAW_XQUNE_4", "SEX_34W", "K2", 0.3092),
    ("RAW_XQUNE_4", "SEX_34E", "K2", -0.3043),
    ("RAW_XQUNE_4", "SEX_35W", "K2", -0.1165),
    ("RAW_XQUNE_4", "SEX_35E", "K2", 0.02589),
    ("RAW_XQUNE_4", "SEX_36W", "K2", -0.4205),
    ("RAW_XQUNE_4", "SEX_36E", "K2", 0.4012),
    ("RAW_XQUNE_4", "SEX_37W", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_37E", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_38W", "K2", -0.09739),
    ("RAW_XQUNE_4", "SEX_38E", "K2", 0.2405),
    ("RAW_XQUNE_4", "SEX_39W", "K2", -0.08696),
    ("RAW_XQUNE_4", "SEX_39E", "K2", -0.2251),
    ("RAW_XQUNE_4", "SEX_40W", "K2", 0.04951),
    ("RAW_XQUNE_4", "SEX_40E", "K2", -0.4485),
    ("RAW_XQUNE_4", "SEX_41W", "K2", 0.2214),
    ("RAW_XQUNE_4", "SEX_41E", "K2", 0.2793),
    ("RAW_XQUNE_4", "SEX_42W", "K2", 0.143),
    ("RAW_XQUNE_4", "SEX_42E", "K2", -0.2775),
    ("RAW_XQUNE_4", "SEX_43W", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_43E", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_44W", "K2", -0.1578),
    ("RAW_XQUNE_4", "SEX_44E", "K2", -0.04028),
    ("RAW_XQUNE_4", "SEX_45W", "K2", 0.0),
    ("RAW_XQUNE_4", "SEX_45E", "K2", 0.0),
    ("RAW_PRETZING_1", "H_SEP_08W", "HKICK", -0.0005061),
    ("RAW_PRETZING_1", "H_SEP_08E", "HKICK", 0.0005061),
    ("RAW_PRETZING_1", "H_SEP_45W", "HKICK", 0.0004739),
    ("RAW_PRETZING_1", "H_SEP_45E", "HKICK", -0.0004739),
    ("RAW_PRETZING_13", "H_SEP_08W", "HKICK", 0.0005061),
    ("RAW_PRETZING_13", "H_SEP_08E", "HKICK", 0.0005061),
    ("RAW_PRETZING_4", "HB01", "HKICK", -0.00055886),
    ("RAW_PRETZING_4", "HB02", "HKICK", -0.0009133),
    ("RAW_PRETZING_4", "H44W", "HKICK", -0.0005286),
    ("RAW_PRETZING_4", "H46W", "HKICK", 0.001049),
    ("RAW_PRETZING_5", "HB06", "HKICK", -0.00055886),
    ("RAW_PRETZING_5", "HB05", "HKICK", -0.0009133),
    ("RAW_PRETZING_5", "H44E", "HKICK", -0.0005286),
    ("RAW_PRETZING_5", "H46E", "HKICK", 0.001049),
    ("RAW_VCROSING_7", "Q49W", "K1", 0.013),
    ("RAW_VCROSING_7", "Q49E", "K1", 0.013),
    ("RAW_VCROSING_7", "Q41W", "K1", -0.003521),
    ("RAW_VCROSING_7", "Q41E", "K1", -0.003521),
    ("RAW_VCROSING_7", "Q42W", "K1", 0.000552),
    ("RAW_VCROSING_7", "Q42E", "K1", 0.000552),
    ("RAW_VCROSING_7", "Q43W", "K1", -0.000409),
    ("RAW_VCROSING_7", "Q43E", "K1", -0.000409),
    ("RAW_VCROSING_7", "Q44W", "K1", -0.003868),
    ("RAW_VCROSING_7", "Q44E", "K1", -0.003868),
    ("RAW_VCROSING_7", "Q45W", "K1", 0.00149),
    ("RAW_VCROSING_7", "Q45E", "K1", 0.00149),
    ("RAW_VCROSING_7", "Q46W", "K1", -0.003516),
    ("RAW_VCROSING_7", "Q46E", "K1", -0.003516),
    ("RAW_VCROSING_7", "Q47W", "K1", -0.000744),
    ("RAW_VCROSING_7", "Q47E", "K1", -0.000744),
    ("RAW_VCROSING_7", "Q47AW", "K1", 0.003933),
    ("RAW_VCROSING_7", "Q47AE", "K1", 0.003933),
    ("RAW_VCROSING_7", "Q48W", "K1", -0.003047),
    ("RAW_VCROSING_7", "Q48E", "K1", -0.003047),
    ("RAW_VCROSING_7", "Q49AW", "K1", 0.000935),
    ("RAW_VCROSING_7", "Q49AE", "K1", 0.000935),
    ("RAW_BETASING_1", "Q03W", "K1", 0.000694),
    ("RAW_BETASING_1", "Q03E", "K1", 0.000694),
    ("RAW_BETASING_1", "Q04W", "K1", 0.000807),
    ("RAW_BETASING_1", "Q04E", "K1", 0.000807),
    ("RAW_BETASING_1", "Q05W", "K1", -0.000699),
    ("RAW_BETASING_1", "Q05E", "K1", -0.000699),
    ("RAW_BETASING_1", "Q06W", "K1", 0.00037),
    ("RAW_BETASING_1", "Q06E", "K1", 0.00037),
    ("RAW_BETASING_1", "Q07W", "K1", -0.001099),
    ("RAW_BETASING_1", "Q07E", "K1", -0.001099),
    ("RAW_BETASING_1", "Q08W", "K1", -0.001112),
    ("RAW_BETASING_1", "Q08E", "K1", -0.001112),
    ("RAW_BETASING_1", "Q09W", "K1", 0.001984),
    ("RAW_BETASING_1", "Q09E", "K1", 0.001984),
    ("RAW_BETASING_1", "Q10W", "K1", -0.000427),
    ("RAW_BETASING_1", "Q10E", "K1", -0.000427),
    ("RAW_BETASING_1", "Q11W", "K1", 0.000504),
    ("RAW_BETASING_1", "Q11E", "K1", 0.000504),
    ("RAW_BETASING_1", "Q12W", "K1", 0.000461),
    ("RAW_BETASING_1", "Q12E", "K1", 0.000461),
    ("RAW_BETASING_1", "Q13W", "K1", -0.001213),
    ("RAW_BETASING_1", "Q13E", "K1", -0.001213),
    ("RAW_BETASING_1", "Q14W", "K1", -1.6e-05),
    ("RAW_BETASING_1", "Q14E", "K1", -1.6e-05),
    ("RAW_BETASING_2", "Q03W", "K1", -0.00033),
    ("RAW_BETASING_2", "Q03E", "K1", -0.00033),
    ("RAW_BETASING_2", "Q04W", "K1", -0.002662),
    ("RAW_BETASING_2", "Q04E", "K1", -0.002662),
    ("RAW_BETASING_2", "Q05W", "K1", 0.000458),
    ("RAW_BETASING_2", "Q05E", "K1", 0.000458),
    ("RAW_BETASING_2", "Q06W", "K1", 0.003894),
    ("RAW_BETASING_2", "Q06E", "K1", 0.003894),
    ("RAW_BETASING_2", "Q07W", "K1", -8.3e-05),
    ("RAW_BETASING_2", "Q07E", "K1", -8.3e-05),
    ("RAW_BETASING_2", "Q08W", "K1", -0.002327),
    ("RAW_BETASING_2", "Q08E", "K1", -0.002327),
    ("RAW_BETASING_2", "Q09W", "K1", 0.000615),
    ("RAW_BETASING_2", "Q09E", "K1", 0.000615),
    ("RAW_BETASING_2", "Q10W", "K1", 0.001338),
    ("RAW_BETASING_2", "Q10E", "K1", 0.001338),
    ("RAW_BETASING_2", "Q11W", "K1", -3.1e-05),
    ("RAW_BETASING_2", "Q11E", "K1", -3.1e-05),
    ("RAW_BETASING_2", "Q12W", "K1", -0.002186),
    ("RAW_BETASING_2", "Q12E", "K1", -0.002186),
    ("RAW_BETASING_2", "Q13W", "K1", 0.000153),
    ("RAW_BETASING_2", "Q13E", "K1", 0.000153),
    ("RAW_BETASING_2", "Q14W", "K1", -0.001851),
    ("RAW_BETASING_2", "Q14E", "K1", -0.001851),
    ("RAW_BETASING_3", "Q03W", "K1", 0.000127),
    ("RAW_BETASING_3", "Q03E", "K1", -0.000127),
    ("RAW_BETASING_3", "Q04W", "K1", 0.000663),
    ("RAW_BETASING_3", "Q04E", "K1", -0.000663),
    ("RAW_BETASING_3", "Q05W", "K1", 0.001625),
    ("RAW_BETASING_3", "Q05E", "K1", -0.001625),
    ("RAW_BETASING_3", "Q06W", "K1", 0.001019),
    ("RAW_BETASING_3", "Q06E", "K1", -0.001019),
    ("RAW_BETASING_3", "Q07W", "K1", -0.001961),
    ("RAW_BETASING_3", "Q07E", "K1", 0.001961),
    ("RAW_BETASING_3", "Q08W", "K1", -0.000957),
    ("RAW_BETASING_3", "Q08E", "K1", 0.000957),
    ("RAW_BETASING_3", "Q09W", "K1", -0.000901),
    ("RAW_BETASING_3", "Q09E", "K1", 0.000901),
    ("RAW_BETASING_3", "Q10W", "K1", 0.001595),
    ("RAW_BETASING_3", "Q10E", "K1", -0.001595),
    ("RAW_BETASING_3", "Q11W", "K1", 0.002316),
    ("RAW_BETASING_3", "Q11E", "K1", -0.002316),
    ("RAW_BETASING_3", "Q12W", "K1", 0.000917),
    ("RAW_BETASING_3", "Q12E", "K1", -0.000917),
    ("RAW_BETASING_3", "Q13W", "K1", 0.000808),
    ("RAW_BETASING_3", "Q13E", "K1", -0.000808),
    ("RAW_BETASING_3", "Q14W", "K1", 0.000686),
    ("RAW_BETASING_3", "Q14E", "K1", -0.000686),
    ("RAW_BETASING_4", "Q01W", "K1", -0.000227),
    ("RAW_BETASING_4", "Q01E", "K1", 0.000227),
    ("RAW_BETASING_4", "Q02W", "K1", -0.000988),
    ("RAW_BETASING_4", "Q02E", "K1", 0.000988),
    ("RAW_BETASING_4", "Q03W", "K1", -0.001856),
    ("RAW_BETASING_4", "Q03E", "K1", 0.001856),
    ("RAW_BETASING_4", "Q04W", "K1", -0.000928),
    ("RAW_BETASING_4", "Q04E", "K1", 0.000928),
    ("RAW_BETASING_4", "Q05W", "K1", 0.002525),
    ("RAW_BETASING_4", "Q05E", "K1", -0.002525),
    ("RAW_BETASING_4", "Q06W", "K1", 0.002742),
    ("RAW_BETASING_4", "Q06E", "K1", -0.002742),
    ("RAW_BETASING_4", "Q07W", "K1", -0.00573),
    ("RAW_BETASING_4", "Q07E", "K1", 0.00573),
    ("RAW_HPHASING_1", "Q01W", "K1", 1e-05),
    ("RAW_HPHASING_1", "Q02W", "K1", 0.000479),
    ("RAW_HPHASING_1", "Q03W", "K1", 0.00195),
    ("RAW_HPHASING_1", "Q04W", "K1", 0.002655),
    ("RAW_HPHASING_1", "Q05W", "K1", -0.000388),
    ("RAW_HPHASING_1", "Q06W", "K1", 0.001682),
    ("RAW_HPHASING_1", "Q07W", "K1", 0.001054),
    ("RAW_HPHASING_1", "Q08W", "K1", 0.004415),
    ("RAW_HPHASING_2", "Q02W", "K1", -0.000288),
    ("RAW_HPHASING_2", "Q03W", "K1", 0.00094),
    ("RAW_HPHASING_2", "Q04W", "K1", 0.003725),
    ("RAW_HPHASING_2", "Q05W", "K1", 0.001001),
    ("RAW_HPHASING_2", "Q06W", "K1", 0.002612),
    ("RAW_HPHASING_2", "Q07W", "K1", 0.000659),
    ("RAW_HPHASING_2", "Q08W", "K1", 0.002009),
    ("RAW_HPHASING_2", "Q09W", "K1", 0.001726),
    ("RAW_HPHASING_3", "Q03W", "K1", 0.000134),
    ("RAW_HPHASING_3", "Q04W", "K1", 0.001683),
    ("RAW_HPHASING_3", "Q05W", "K1", 0.000352),
    ("RAW_HPHASING_3", "Q06W", "K1", 0.00163),
    ("RAW_HPHASING_3", "Q07W", "K1", 0.00044),
    ("RAW_HPHASING_3", "Q08W", "K1", -0.0002),
    ("RAW_HPHASING_3", "Q09W", "K1", 0.000125),
    ("RAW_HPHASING_3", "Q10W", "K1", 0.002144),
    ("ASYM_IR", "Q00W", "TILT", -0.005394),
    ("ASYM_IR", "Q00E", "TILT", 0.005394),
    ("ASYM_IR", "Q01W", "TILT", -0.008269),
    ("ASYM_IR", "Q01E", "TILT", 0.008269),
    ("ASYM_IR", "Q02W", "TILT", -0.016),
    ("ASYM_IR", "Q02E", "TILT", 0.016),
    ("SYM_IR", "Q00W", "TILT", -0.00198),
    ("SYM_IR", "Q00E", "TILT", -0.00198),
    ("SYM_IR", "Q01W", "TILT", -0.00262),
    ("SYM_IR", "Q01E", "TILT", -0.00262),
    ("SYM_IR", "Q02W", "TILT", -0.006),
    ("SYM_IR", "Q02E", "TILT", -0.006),
    ("CV_CO_ANGLE_Y", "Q00W", "TILT", 0.013069),
    ("CV_CO_ANGLE_Y", "Q01W", "TILT", 0.017714),
    ("CV_CO_ANGLE_Y", "Q02W", "TILT", 0.043352),
    ("CV_CO_ANGLE_Y", "Q00E", "TILT", 0.013085),
    ("CV_CO_ANGLE_Y", "Q01E", "TILT", 0.017717),
    ("CV_CO_ANGLE_Y", "Q02E", "TILT", 0.04179),
    ("CV_L0_DISP_Y", "Q00W", "TILT", -0.003701),
    ("CV_L0_DISP_Y", "Q00E", "TILT", 0.003701),
    ("CV_L0_DISP_Y", "Q01W", "TILT", -0.005684),
    ("CV_L0_DISP_Y", "Q01E", "TILT", 0.005684),
    ("CV_L0_DISP_Y", "Q02W", "TILT", -0.011093),
    ("CV_L0_DISP_Y", "Q02E", "TILT", 0.011093),
    ("ASYM_Q0", "Q00W", "TILT", 1.0),
    ("ASYM_Q0", "Q00E", "TILT", -1.0),
    ("ASYM_Q1", "Q01W", "TILT", 1.0),
    ("ASYM_Q1", "Q01E", "TILT", -1.0),
    ("ASYM_Q2", "Q02W", "TILT", 1.0),
    ("ASYM_Q2", "Q02E", "TILT", -1.0),
    ("SYM_Q0", "Q00W", "TILT", 1.0),
    ("SYM_Q0", "Q00E", "TILT", 1.0),
    ("SYM_Q1", "Q01W", "TILT", 1.0),
    ("SYM_Q1", "Q01E", "TILT", 1.0),
    ("SYM_Q2", "Q02W", "TILT", 1.0),
    ("SYM_Q2", "Q02E", "TILT", 1.0),
]


const _CESR_ATTRIBUTE_MAP = Dict(
    "K1" => :Kn1,
    "K2" => :Kn2,
    "TILT" => :tilt,
)

"""Construct zero-valued CESR controls. Pass a typed zero for TPS knobs."""
function CESRControls(zero_value::T=0.0) where {T}
    overlay_names = unique(term[1] for term in CESR_OVERLAY_TERMS)
    group_names = unique(term[1] for term in CESR_GROUP_TERMS)
    overlays = Dict(name => CESRControlKnob{T}(zero_value) for name in overlay_names)
    groups = Dict(name => CESRControlKnob{T}(zero_value) for name in group_names)
    return CESRControls{T}(overlays, groups)
end

"""Return a sorted list of available CESR control names."""
function cesr_control_names(controls::CESRControls; kind::Symbol=:all)
    if kind === :overlay
        return sort!(collect(keys(controls.overlays)))
    elseif kind === :group
        return sort!(collect(keys(controls.groups)))
    elseif kind === :all
        return sort!(vcat(collect(keys(controls.overlays)), collect(keys(controls.groups))))
    end
    error("kind must be :overlay, :group, or :all")
end

function _cesr_control_knob(controls::CESRControls, name::AbstractString)
    key = uppercase(String(name))
    if haskey(controls.overlays, key)
        return controls.overlays[key]
    elseif haskey(controls.groups, key)
        return controls.groups[key]
    end
    error("Unknown CESR control: $name")
end

"""Read a CESR overlay or group knob value by its Bmad name."""
get_cesr_control(controls::CESRControls, name::AbstractString) =
    _cesr_control_knob(controls, name).value

"""Set a CESR overlay or group knob by its Bmad name."""
function set_cesr_control!(controls::CESRControls{T}, name::AbstractString, value) where {T}
    knob = _cesr_control_knob(controls, name)
    knob.value = convert(T, value)
    return controls
end

Base.getindex(controls::CESRControls, name::AbstractString) =
    get_cesr_control(controls, name)
Base.setindex!(controls::CESRControls, value, name::AbstractString) =
    set_cesr_control!(controls, name, value)

function _cesr_name(ele)
    return uppercase(String(ele.name))
end

function _cesr_target_elements(ring, bmad_name::String)
    exact = [ele for ele in ring.line if _cesr_name(ele) == bmad_name]
    !isempty(exact) && return exact

    # Superposed Bmad elements are split into names such as Q00W!MCLEO_SOL and
    # Q00W!S1. A control on Q00W must drive every one of those slices.
    prefix = bmad_name * "!"
    slices = [ele for ele in ring.line if startswith(_cesr_name(ele), prefix)]
    !isempty(slices) && return slices
    error("CESR control target $bmad_name was not found in the supplied ring")
end

function _cesr_add_contribution!(table, target, attribute, contribution)
    key = (target, attribute)
    push!(get!(table, key, CESRControlContribution[]), contribution)
    return table
end

"""
Translate a Bmad control attribute into SciBmad element-frame multipoles.

Bmad `HKICK` and `VKICK` are laboratory-frame orbit kicks. SciBmad's normal
and skew dipole multipoles use the magnetic sign convention and rotate with an
element's alignment tilt, so a kick generally drives both `Kn0L` and `Ks0L`.
"""
function _cesr_physical_control_terms(ring, target, bmad_attribute, coefficient)
    if bmad_attribute == "HKICK" || bmad_attribute == "VKICK"
        elements = _cesr_target_elements(ring, target)
        tilts = Float64[Beamlines.deval(ele.tilt) for ele in elements]
        all(isapprox(tilt, first(tilts); atol=1e-14, rtol=0.0) for tilt in tilts) ||
            error("Kick target $target has slices with different alignment tilts")

        tilt = first(tilts)
        physical_terms = if bmad_attribute == "HKICK"
            ((:Kn0L, -coefficient * cos(tilt)),
             (:Ks0L, -coefficient * sin(tilt)))
        else
            ((:Kn0L, -coefficient * sin(tilt)),
             (:Ks0L, coefficient * cos(tilt)))
        end
        return [(target, attribute, physical_coefficient)
                for (attribute, physical_coefficient) in physical_terms
                if !iszero(physical_coefficient)]
    end

    attribute = get(_CESR_ATTRIBUTE_MAP, bmad_attribute) do
        error("Unsupported Bmad control attribute: $bmad_attribute")
    end
    return [(target, attribute, coefficient)]
end

"""
    attach_cesr_controls!(ring; zero_value=0.0)

Attach all Bmad CESR Overlay and Group definitions to a copied static ring using
`DefExpr`. The element values in `ring` become the zero-control baselines.

Group-to-overlay relationships are composed before expressions are attached, so
changing a group knob propagates through the overlay to each physical element.
The returned `CESRControls` owns the mutable knob values.
"""
function attach_cesr_controls!(ring; zero_value=0.0)
    controls = CESRControls(zero_value)
    contributions = Dict{Tuple{String,Symbol},Vector{CESRControlContribution}}()
    overlay_targets = Dict{String,Vector{Tuple{String,Symbol,Float64}}}()
    overlay_variables = Dict{String,String}()

    for (overlay, variable, target, coefficient) in CESR_OVERLAY_TERMS
        overlay_variables[overlay] = variable
        for (physical_target, attribute, physical_coefficient) in
            _cesr_physical_control_terms(ring, target, variable, coefficient)
            push!(get!(overlay_targets, overlay, Tuple{String,Symbol,Float64}[]),
                  (physical_target, attribute, physical_coefficient))
            contribution = CESRControlContribution(
                controls.overlays[overlay],
                physical_coefficient,
            )
            _cesr_add_contribution!(
                contributions,
                physical_target,
                attribute,
                contribution,
            )
        end
    end

    overlay_names = Set(keys(overlay_targets))
    for (group, target, bmad_attribute, coefficient) in CESR_GROUP_TERMS
        group_knob = controls.groups[group]
        if target in overlay_names
            if !isempty(bmad_attribute) && bmad_attribute != overlay_variables[target]
                error(
                    "Group $group targets overlay $target[$bmad_attribute], but its " *
                    "control variable is $(overlay_variables[target])",
                )
            end
            for (physical_target, attribute, overlay_coefficient) in overlay_targets[target]
                contribution = CESRControlContribution(
                    group_knob,
                    coefficient * overlay_coefficient,
                )
                _cesr_add_contribution!(
                    contributions,
                    physical_target,
                    attribute,
                    contribution,
                )
            end
        else
            isempty(bmad_attribute) && error(
                "Group $group targets physical element $target without an attribute",
            )
            for (physical_target, attribute, physical_coefficient) in
                _cesr_physical_control_terms(ring, target, bmad_attribute, coefficient)
                contribution = CESRControlContribution(group_knob, physical_coefficient)
                _cesr_add_contribution!(
                    contributions,
                    physical_target,
                    attribute,
                    contribution,
                )
            end
        end
    end

    attached = 0
    for ((target, attribute), terms) in contributions
        for ele in _cesr_target_elements(ring, target)
            baseline = Beamlines.deval(getproperty(ele, attribute))
            expression = DefExpr(() -> begin
                value = baseline
                for term in terms
                    value += term.coefficient * term.knob.value
                end
                value
            end)
            setproperty!(ele, attribute, expression)
            attached += 1
        end
    end

    return controls
end
