"""Generate cesr_controls.jl from the control definitions in cesr.bmad.

The generated Julia file is self-contained: it does not read the Bmad lattice at
runtime. Re-run this script only when the control section of cesr.bmad changes.
"""

from __future__ import annotations

import re
from pathlib import Path


HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
SOURCE = PROJECT_ROOT / "cesr.bmad"
OUTPUT = PROJECT_ROOT / "cesr_controls.jl"


CONTROL_RE = re.compile(
    r"(?ms)^\s*([A-Za-z0-9_]+)\s*:\s*(overlay|group)\s*=\s*"
    r"\{(.*?)\}\s*,\s*var\s*=\s*\{([A-Za-z0-9_]+)\}"
)
TARGET_RE = re.compile(
    r"^\s*([A-Za-z0-9_]+)(?:\[([A-Za-z0-9_]+)\])?"
    r"(?:\s*:\s*(.*))?\s*$"
)


def parse_coefficient(expression: str | None, variable: str) -> float:
    if expression is None or not expression.strip():
        return 1.0
    expression = re.sub(r"\s+", "", expression).upper()
    variable = variable.upper()
    if expression == variable:
        return 1.0
    suffix = "*" + variable
    if not expression.endswith(suffix):
        raise ValueError(f"Unsupported control expression: {expression}")
    coefficient = expression[: -len(suffix)]
    if coefficient in ("", "+"):
        return 1.0
    if coefficient == "-":
        return -1.0
    return float(coefficient.replace("D", "E"))


def parse_controls(text: str):
    overlays: list[tuple[str, str, str, float]] = []
    groups: list[tuple[str, str, str, float]] = []
    definitions: list[tuple[str, str]] = []

    for match in CONTROL_RE.finditer(text):
        name, kind, body, variable = match.groups()
        name = name.upper()
        variable = variable.upper()
        definitions.append((kind, name))
        for raw_target in body.split(","):
            target_match = TARGET_RE.match(raw_target)
            if target_match is None:
                raise ValueError(f"Cannot parse target in {name}: {raw_target!r}")
            target, attribute, expression = target_match.groups()
            target = target.upper()
            coefficient = parse_coefficient(expression, variable)
            if kind == "overlay":
                if attribute is not None:
                    raise ValueError(f"Overlay {name} unexpectedly specifies [{attribute}]")
                overlays.append((name, variable, target, coefficient))
            else:
                if attribute is None:
                    # A group may target an overlay without spelling out its variable.
                    attribute = ""
                groups.append((name, target, attribute.upper(), coefficient))

    if not overlays or not groups:
        raise RuntimeError("No overlay/group controls were found in cesr.bmad")
    return definitions, overlays, groups


def julia_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_tuple_rows(rows) -> str:
    lines = []
    for row in rows:
        rendered = ", ".join(
            julia_string(value) if isinstance(value, str) else repr(value) for value in row
        )
        lines.append(f"    ({rendered}),")
    return "\n".join(lines)


JULIA_PREAMBLE = r'''# This file is generated by generate_cesr_controls.py from cesr.bmad.
# Do not hand-edit the coefficient tables. The runtime implementation below may
# be edited, but regenerate carefully because this script rewrites the full file.

using Beamlines

"""One mutable scalar used by a CESR control knob."""
mutable struct CESRControlKnob{T}
    value::T
end

"""All CESR overlay and group knobs attached to one ring."""
struct CESRControls{T}
    overlays::Dict{String,CESRControlKnob{T}}
    groups::Dict{String,CESRControlKnob{T}}
end

"""A physical element attribute driven by one control knob."""
struct CESRControlContribution{T}
    knob::CESRControlKnob{T}
    coefficient::Float64
end

'''


JULIA_RUNTIME = r'''

const _CESR_ATTRIBUTE_MAP = Dict(
    "K1" => :Kn1,
    "K2" => :Kn2,
    "TILT" => :tilt,
)

"""Construct zero-valued CESR controls. Pass a typed zero for TPS knobs."""
function CESRControls(zero_value::T=0.0) where {T}
    overlay_names = unique(term[1] for term in CESR_OVERLAY_TERMS)
    group_names = unique(term[1] for term in CESR_GROUP_TERMS)
    overlays = Dict(name => CESRControlKnob{T}(zero_value) for name in overlay_names)
    groups = Dict(name => CESRControlKnob{T}(zero_value) for name in group_names)
    return CESRControls{T}(overlays, groups)
end

"""Return a sorted list of available CESR control names."""
function cesr_control_names(controls::CESRControls; kind::Symbol=:all)
    if kind === :overlay
        return sort!(collect(keys(controls.overlays)))
    elseif kind === :group
        return sort!(collect(keys(controls.groups)))
    elseif kind === :all
        return sort!(vcat(collect(keys(controls.overlays)), collect(keys(controls.groups))))
    end
    error("kind must be :overlay, :group, or :all")
end

function _cesr_control_knob(controls::CESRControls, name::AbstractString)
    key = uppercase(String(name))
    if haskey(controls.overlays, key)
        return controls.overlays[key]
    elseif haskey(controls.groups, key)
        return controls.groups[key]
    end
    error("Unknown CESR control: $name")
end

"""Read a CESR overlay or group knob value by its Bmad name."""
get_cesr_control(controls::CESRControls, name::AbstractString) =
    _cesr_control_knob(controls, name).value

"""Set a CESR overlay or group knob by its Bmad name."""
function set_cesr_control!(controls::CESRControls{T}, name::AbstractString, value) where {T}
    knob = _cesr_control_knob(controls, name)
    knob.value = convert(T, value)
    return controls
end

Base.getindex(controls::CESRControls, name::AbstractString) =
    get_cesr_control(controls, name)
Base.setindex!(controls::CESRControls, value, name::AbstractString) =
    set_cesr_control!(controls, name, value)

function _cesr_name(ele)
    return uppercase(String(ele.name))
end

function _cesr_target_elements(ring, bmad_name::String)
    exact = [ele for ele in ring.line if _cesr_name(ele) == bmad_name]
    !isempty(exact) && return exact

    # Superposed Bmad elements are split into names such as Q00W!MCLEO_SOL and
    # Q00W!S1. A control on Q00W must drive every one of those slices.
    prefix = bmad_name * "!"
    slices = [ele for ele in ring.line if startswith(_cesr_name(ele), prefix)]
    !isempty(slices) && return slices
    error("CESR control target $bmad_name was not found in the supplied ring")
end

function _cesr_add_contribution!(table, target, attribute, contribution)
    key = (target, attribute)
    push!(get!(table, key, CESRControlContribution[]), contribution)
    return table
end

"""
Translate a Bmad control attribute into SciBmad element-frame multipoles.

Bmad `HKICK` and `VKICK` are laboratory-frame orbit kicks. SciBmad's normal
and skew dipole multipoles use the magnetic sign convention and rotate with an
element's alignment tilt, so a kick generally drives both `Kn0L` and `Ks0L`.
"""
function _cesr_physical_control_terms(ring, target, bmad_attribute, coefficient)
    if bmad_attribute == "HKICK" || bmad_attribute == "VKICK"
        elements = _cesr_target_elements(ring, target)
        tilts = Float64[Beamlines.deval(ele.tilt) for ele in elements]
        all(isapprox(tilt, first(tilts); atol=1e-14, rtol=0.0) for tilt in tilts) ||
            error("Kick target $target has slices with different alignment tilts")

        tilt = first(tilts)
        physical_terms = if bmad_attribute == "HKICK"
            ((:Kn0L, -coefficient * cos(tilt)),
             (:Ks0L, -coefficient * sin(tilt)))
        else
            ((:Kn0L, -coefficient * sin(tilt)),
             (:Ks0L, coefficient * cos(tilt)))
        end
        return [(target, attribute, physical_coefficient)
                for (attribute, physical_coefficient) in physical_terms
                if !iszero(physical_coefficient)]
    end

    attribute = get(_CESR_ATTRIBUTE_MAP, bmad_attribute) do
        error("Unsupported Bmad control attribute: $bmad_attribute")
    end
    return [(target, attribute, coefficient)]
end

"""
    attach_cesr_controls!(ring; zero_value=0.0)

Attach all Bmad CESR Overlay and Group definitions to a copied static ring using
`DefExpr`. The element values in `ring` become the zero-control baselines.

Group-to-overlay relationships are composed before expressions are attached, so
changing a group knob propagates through the overlay to each physical element.
The returned `CESRControls` owns the mutable knob values.
"""
function attach_cesr_controls!(ring; zero_value=0.0)
    controls = CESRControls(zero_value)
    contributions = Dict{Tuple{String,Symbol},Vector{CESRControlContribution}}()
    overlay_targets = Dict{String,Vector{Tuple{String,Symbol,Float64}}}()
    overlay_variables = Dict{String,String}()

    for (overlay, variable, target, coefficient) in CESR_OVERLAY_TERMS
        overlay_variables[overlay] = variable
        for (physical_target, attribute, physical_coefficient) in
            _cesr_physical_control_terms(ring, target, variable, coefficient)
            push!(get!(overlay_targets, overlay, Tuple{String,Symbol,Float64}[]),
                  (physical_target, attribute, physical_coefficient))
            contribution = CESRControlContribution(
                controls.overlays[overlay],
                physical_coefficient,
            )
            _cesr_add_contribution!(
                contributions,
                physical_target,
                attribute,
                contribution,
            )
        end
    end

    overlay_names = Set(keys(overlay_targets))
    for (group, target, bmad_attribute, coefficient) in CESR_GROUP_TERMS
        group_knob = controls.groups[group]
        if target in overlay_names
            if !isempty(bmad_attribute) && bmad_attribute != overlay_variables[target]
                error(
                    "Group $group targets overlay $target[$bmad_attribute], but its " *
                    "control variable is $(overlay_variables[target])",
                )
            end
            for (physical_target, attribute, overlay_coefficient) in overlay_targets[target]
                contribution = CESRControlContribution(
                    group_knob,
                    coefficient * overlay_coefficient,
                )
                _cesr_add_contribution!(
                    contributions,
                    physical_target,
                    attribute,
                    contribution,
                )
            end
        else
            isempty(bmad_attribute) && error(
                "Group $group targets physical element $target without an attribute",
            )
            for (physical_target, attribute, physical_coefficient) in
                _cesr_physical_control_terms(ring, target, bmad_attribute, coefficient)
                contribution = CESRControlContribution(group_knob, physical_coefficient)
                _cesr_add_contribution!(
                    contributions,
                    physical_target,
                    attribute,
                    contribution,
                )
            end
        end
    end

    attached = 0
    for ((target, attribute), terms) in contributions
        for ele in _cesr_target_elements(ring, target)
            baseline = Beamlines.deval(getproperty(ele, attribute))
            expression = DefExpr(() -> begin
                value = baseline
                for term in terms
                    value += term.coefficient * term.knob.value
                end
                value
            end)
            setproperty!(ele, attribute, expression)
            attached += 1
        end
    end

    return controls
end
'''


def main() -> None:
    definitions, overlays, groups = parse_controls(SOURCE.read_text(encoding="utf-8"))
    overlay_names = {name for kind, name in definitions if kind == "overlay"}
    group_names = {name for kind, name in definitions if kind == "group"}
    if len(overlay_names) != 119:
        raise RuntimeError(f"Expected 119 overlays, found {len(overlay_names)}")
    if len(group_names) != 26:
        raise RuntimeError(f"Expected 26 groups, found {len(group_names)}")

    generated = JULIA_PREAMBLE
    generated += "const CESR_OVERLAY_TERMS = [\n"
    generated += emit_tuple_rows(overlays)
    generated += "\n]\n\n"
    generated += "const CESR_GROUP_TERMS = [\n"
    generated += emit_tuple_rows(groups)
    generated += "\n]\n"
    generated += JULIA_RUNTIME
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(
        f"Wrote {OUTPUT.name}: {len(overlay_names)} overlays / {len(overlays)} terms, "
        f"{len(group_names)} groups / {len(groups)} terms"
    )


if __name__ == "__main__":
    main()
